sudo: required
language: python

services:
  - docker

matrix:
  include:
  - python: 3.6
    env: TOXENV=flake8
  - python: 3.6
    env: TOXENV=py36

install:
- pip install tox

script:
- tox -e $TOXENV
